/**
 * 医院挂号系统
 * Date: 2021-06-29
 * Author: Henry Wang
 * */
package com;

import java.util.ArrayList;

import javax.swing.JOptionPane;


/**
 * 医生端窗口
 */
public class CustomFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJFrame1
     */
    public CustomFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	 jLabel1 = new javax.swing.JLabel();
         jLabel2 = new javax.swing.JLabel();
         jComboBox2 = new javax.swing.JComboBox<>();
         jButton1 = new javax.swing.JButton();
         jLabel3 = new javax.swing.JLabel();
         jLabel4 = new javax.swing.JLabel();
         jLabel5 = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
         jTable1 = new javax.swing.JTable();
         jButton2 = new javax.swing.JButton();
         jButton3 = new javax.swing.JButton();

         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         setTitle("挂号系统医生端");

         //获取姓名
         String sql = "select name from yonghu_tab where id = '";
         sql = sql + LogDialog.userid+"'";
         String[][] results = Main.toArray(Main.select(sql, 1));
         jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jLabel1.setText("您好:"+results[0][0]);

         jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jLabel2.setText("我的状态：");

         jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"请选择","在岗", "不在岗" }));

         jButton1.setText("更新状态");
         jButton1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton1ActionPerformed(evt);
             }
         });

         jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jLabel3.setText("病人数：");

         jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jLabel4.setText("当前病人：");

         jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jLabel5.setText("当前病人往日诊疗记录");

         jTable1.setModel(new javax.swing.table.DefaultTableModel(
             new Object [][] {
                 {null, null, null, null},
                 {null, null, null, null},
                 {null, null, null, null},
                 {null, null, null, null}
             },
             new String [] {
                 "id", "病人", "医生", "时间","病情描述"
             }
         ));
         jScrollPane1.setViewportView(jTable1);

         jButton2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jButton2.setText("下一位");
         jButton2.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton2ActionPerformed(evt);
             }
         });

         jButton3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
         jButton3.setText("填写病历");
         jButton3.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton3ActionPerformed(evt);
             }
         });

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addGroup(layout.createSequentialGroup()
                                 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                             .addGroup(layout.createSequentialGroup()
                                 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addGap(18, 18, 18)
                                 .addComponent(jLabel2)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                         .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(30, 30, 30)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(jLabel2)
                     .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton1))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3)
                     .addComponent(jLabel4))
                 .addGap(18, 18, 18)
                 .addComponent(jLabel5)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                         .addComponent(jButton2)
                         .addGap(18, 18, 18)
                         .addComponent(jButton3)))
                 .addContainerGap(18, Short.MAX_VALUE))
         );

         pack();
    }// </editor-fold>  
    
    /**更新状态按钮
     * */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	//设置在岗与不在岗
    	String sql = "update yuangong_tab set zaigang = ";
    	if(jComboBox2.getSelectedIndex() == 1) {
    		sql = sql + 1 + " where name = ";
    	}else {
    		sql = sql + 0 + " where name = ";
    	}
    	//获取姓名
        String t_sql = "select name from yonghu_tab where id = '";
        t_sql = t_sql + LogDialog.userid+"'";
        String[][] results = Main.toArray(Main.select(t_sql, 1));
    	String name = results[0][0];
		sql = sql + "'" + name + "'";
    	Main.update(sql);//更改在岗状况
    	System.out.println(sql);
    	JOptionPane.showMessageDialog(this, "修改成功", "温馨提示", 1);
    	//获取排队病人数
    	sql = "select COUNT(*) from jiezhen_tab where doctor = ";
    	sql = sql + "'" + name + "' ";
    	sql = sql + "and chuli = 0";
    	System.out.println(sql);
    	ArrayList<ArrayList<String>> result = Main.select(sql, 1);
    	jLabel3.setText("病人数:"+result.get(0).get(0));
    	//获取当前病人名称
    	sql = "select patient "
    			+ "from jiezhen_tab where doctor = ";
    	sql = sql + "'" + name + "' and chuli = 0";
    	String[][] t_result = Main.toArray(Main.select(sql, 1));
    	jLabel4.setText("当前病人:"+t_result[0][0]);
    	//获取该病人往日诊疗信息
    	sql = "select id,patient,doctor,time,miaoshu "
    			+ "from jiezhen_tab where patient = ";
    	sql = sql + "'" + t_result[0][0] + "' and chuli = 1";
    	System.out.println(sql);
    	t_result = Main.toArray(Main.select(sql, 5));
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                t_result,
                new String [] {
                    "id", "病人", "医生", "时间", "病情描述"
                }
            ));
    }      
    
    /**"下一个"按钮
     * */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	//将当前病人设置为已处理
    	//获取姓名
        String t_sql = "select name from yonghu_tab where id = '";
        t_sql = t_sql + LogDialog.userid+"'";
        String[][] results = Main.toArray(Main.select(t_sql, 1));
    	String name = results[0][0];
    	String sql = "select * "
    			+ "from jiezhen_tab where doctor = ";
    	sql = sql + "'" + name + "' and chuli = 0";
    	String[][] t_result = Main.toArray(Main.select(sql, 6));
    	String id = t_result[0][0];
    	sql = "update jiezhen_tab set chuli = 1 where id = '"
    			+ id + "'";
    	System.out.println(sql);
    	Main.update(sql);
    	//获取排队人数
    	sql = "select COUNT(*) from jiezhen_tab where doctor = ";
    	sql = sql + "'" + name + "' ";
    	sql = sql + "and chuli = 0";
    	System.out.println(sql);
    	ArrayList<ArrayList<String>> result = Main.select(sql, 1);
    	jLabel3.setText("病人数:"+result.get(0).get(0));
    	//获取当前病人名称
    	sql = "select patient "
    			+ "from jiezhen_tab where doctor = ";
    	sql = sql + "'" + name + "' and chuli = 0";
    	t_result = Main.toArray(Main.select(sql, 1));
    	jLabel4.setText("当前病人:"+t_result[0][0]);
    	//获取该病人往日诊疗信息
    	sql = "select id,patient,doctor,time,miaoshu "
    			+ "from jiezhen_tab where patient = ";
    	sql = sql + "'" + t_result[0][0] + "' and chuli = 1";
    	sql = sql + " order by time";
    	System.out.println(sql);
    	t_result = Main.toArray(Main.select(sql, 5));
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                t_result,
                new String [] {
                    "id", "病人", "医生", "时间", "病情描述"
                }
            ));
    }        
    
    /**填写病历按钮
     * */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	new BlFrame().setVisible(true);
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}

